#ifndef ERROR_CODES_H
#define ERROR_CODES_H

typedef enum {
    DOMO_OK = 0,
    DOMO_ERR_DEVICE_NOT_FOUND = 1,
    DOMO_ERR_INVALID_COMMAND = 2,
    DOMO_ERR_IPC_FAILURE = 3,
    DOMO_ERR_INVALID_PARAMETERS = 4,
    DOMO_ERR_LINK_FAILED = 5,
    DOMO_ERR_DEVICE_TYPE_MISMATCH = 6,
    DOMO_ERR_ALREADY_LINKED = 7,
    DOMO_ERR_SELF_LINK = 8,
    DOMO_ERR_CYCLE_DETECTED = 9,
    DOMO_ERR_NOT_ALLOWED = 10,
    DOMO_ERR_CHILD_CRASHED = 11,
    DOMO_ERR_TIMEOUT = 12,
    DOMO_ERR_INVALID_STATE = 13,
    DOMO_ERR_INVALID_TIME = 14,
    DOMO_ERR_SYSTEM = 100
} domo_error_t;

const char *domo_error_str(int code);

#endif